cse_a/views.py
from flask import Blueprint,request,redirect,url_for
from flask import render_template,request
import os
from flask import current_app
from cse_a import app
from cse_a.models import Message,db,Attendance,Cse_Gallery,Technical
from PIL import Image
from cse_a.forms import Gallery
import datetime
import boto3
import requests
import json

core = Blueprint('core',__name__)
s3 = boto3.client('s3', aws_access_key_id='AKIAURANAD5QSGAU4AO3', aws_secret_access_key='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')
bucket_name='cse-static-a'


@core.route('/')
def index():
    return render_template('index.html')

@core.route("/pccn")
def pccn():
    return render_template('pccn.html')

@core.route("/mc")
def mc():
    return render_template("mc.html")

@core.route("/cns")
def cns():
    return render_template("cns.html")

@core.route("/cd")
def cd():
    return render_template("cd.html")

@core.route("/wt")
def wt():
    return render_template("wt.html")


@core.route("/donate")
def donate():
    return render_template('donate.html')


@core.route('/contact',methods=['GET','POST'])
def contact():
    if request.method=="GET":

        return render_template('contact.html')
    else:
        name =  request.form['name']
        email = request.form['email']
        message = request.form['message']

        entry = Message(name,email,message)
        db.session.add(entry)
        db.session.commit()

        return render_template('feedback.html',name=name,email=email,message=message)

@core.route('/upcomingEvents')
def upcomingEvents():
    return render_template('blog.html')


@core.route('/about')
def about():
    names = ['me1.png','devank.jpg','yashwanth.jpg','aswin.jpg']
    urls=[]
    for i in names:
        url = s3.generate_presigned_url(ClientMethod='get_object',
                                Params={
                                    'Bucket': bucket_name,
                                    'Key': 'developers/{}'.format(i),
                                },
                                ExpiresIn=3600)
        urls.append(url)

    return render_template('about.html',urls=urls)

@core.route('/attendance_add',methods=['POST','GET'])
def attendance_add():
    present = request.form['present']
    row = Attendance(present=present)
    db.session.add(row)
    db.session.commit()


    return redirect(url_for('core.attendance'))

@core.route('/gallery')
def gallery():
    urls=[]
    images = Cse_Gallery.query.all()
    for i in images:
        url = s3.generate_presigned_url(ClientMethod='get_object',
                                Params={
                                    'Bucket': bucket_name,
                                    'Key': 'Images/{}'.format(i.name),
                                },
                                ExpiresIn=3600)
        urls.append(url)


    return render_template('gallery.html', images=urls)


@core.route('/timeTable')
def timeTable():
    return render_template('timetable.html')


@core.route('/assignments')
def assignments():
    return render_template('blog-single.html')

@core.route('/attendance')
def attendance():
    date = datetime.datetime.now()
    a = Attendance.query.order_by(Attendance.date.desc())
    return render_template('attendance.html',a = a,date=date)

@core.route('/upload_gallery',methods=['POST','GET'])
def upload():
    try:
        error = None
        form = Gallery()
        if request.method=="POST":
            if form.validate_on_submit:
                if form.options.data=='image':
                    if form.file.data:
                        try:
                            file = form.file.data
                            filename = file.filename
                            image = Cse_Gallery(name=filename)
                            db.session.add(image)
                            db.session.commit()

                            s3.put_object(Body=file,
                                      Bucket=bucket_name,
                                      Key='Images/{}'.format(filename),

                                )
                            return("<h1>upload successful<h1>")
                        except Exception as e:
                            return (str(e))

                elif form.options.data=='pdf':
                    try:
                        pdf = form.file.data
                        filename = pdf.filename
                        s3.put_object(Body=pdf,
                                      Bucket=bucket_name,
                                      Key='pdfs/{}'.format(filename) )
                    except Exception as e:
                        return (str(e))


            return render_template('upload.html',form=form,error=error)
        return render_template('upload.html',form=form,error=error)
    except:
        error = 'Try again............'
        return render_template('upload.html',form=form,error=error)

@core.route('/challenge/<int:id>',methods=["POST","GET"])
def challenge(id):
    output = None
    code = None
    ele = Technical.query.filter_by(id=id).first()
    languages = {"ada": 53,"bash": 14, "brainfuck": 19, "c": 1,"clojure": 13,"cobol": 36, "coffeescript": 59, "cpp": 2, "cpp14": 58,
             "csharp": 9,"db2": 44,"elixir": 52, "erlang": 16, "fortran": 54,"fsharp": 33, "go": 21, "groovy": 31,
             "haskell": 12, "haxe": 69, "java": 3, "nodejs": 20,"julia": 57, "kotlin": 71, "lolcode": 38, "lua": 18,
             "maven": 45, "mysql": 10, "prolog": 64, "objectivec": 32, "ocaml": 23, "octave": 46, "oracle": 11,
             "pascal": 25, "perl": 6, "php": 7, "pypy": 61, "pypy3": 62,"python2": 5, "python3": 30, "r": 24, "racket": 49, "ruby": 8,
             "rust": 50, "d": 26, "sbt": 70,"scala": 15, "smalltalk": 39, "swift": 51, "tcl": 40, "text": 28,
             "tsql": 42, "visualbasic": 37, "whitespace": 41, "unlamda": 48
             }
    if request.method=='POST':
        def solve(code,input_,lang):

            content = {'content-type':'application/json'}
            if input_=='':
                input_=' '

            url = 'https://api.jdoodle.com/v1/execute'

            data = {
                            'script': code,
                            'language': lang,
                            'stdin':input_,
                            'versionIndex': '0',
                            'clientId': 'b294d436264a9f669f8e8810318c01c2',
                            'clientSecret': '90a81d009c2a15ed2d7603b671b36369495ff024f5f0b6cecc2b20d0b6d0019',
                }
            response = requests.post(url,data=json.dumps(data),headers=content)
            res=response.json()

            return res

        lang = request.form.get('lang')
        code = request.form.get('code')
        input_ = request.form.get('input')
        output = solve(code,input_,lang)
        return render_template("challenge.html",output=output,code=code,ele=ele,languages=languages)




    return render_template('challenge.html',ele=ele,languages=languages,output=output,code=code)


@core.route('/technical')
def technical():
    challenges = Technical.query.all()
    return render_template('technical.html',challenges=challenges)

cse_a/templates/attendance.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Cse-a</title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Overpass:300,400,500|Dosis:400,700" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/open-iconic-bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/animate.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/owl.theme.default.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/magnific-popup.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/aos.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/ionicons.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap-datepicker.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/jquery.timepicker.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/flaticon.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/icomoon.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/fancybox.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">

  </head>
  <style media="screen">


  </style>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-dark" id="ftco-navbar">
      <div class="container">
        <a class="navbar-brand" href="index.html">CSE-A</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
          <ul class="navbar-nav ml-auto">
            <li id='mm' class="nav-item "><a href="{{url_for('core.index')}}" class="nav-link">Home</a></li>
            <li class="nav-item "><a href="{{url_for('core.donate')}}" class="nav-link">Assignments</a></li>
            <li class="nav-item"><a href="{{url_for("core.timeTable")}}" class="nav-link">Time table</a></li>
            <li class="nav-item"><a href="{{url_for("core.gallery")}}" class="nav-link">Gallery</a></li>
            <li class="nav-item"><a href="{{url_for('core.attendance')}}" class="nav-link">Attendance</a></li>
            <li class="nav-item"><a href="{{url_for('core.about')}}" class="nav-link">About</a></li>
            <li class="nav-item"><a href="{{url_for('core.contact')}}" class="nav-link">Contact</a></li>

          </ul>
        </div>
      </div>
    </nav>

<br><br><br><br>
<div class="container">
    <div class="row">
        <div class="col md-12">

            <div class="jumbotron p-3">

                <h2>3 CSE -A <b> Attendance </b>  <button type="button"  class="btn btn-success float-right"
                data-toggle="modal" data-target="#mymodal">Add Entry</button> </h2>


                {% with messages = get_flashed_messages() %}

                {% if messages %}

                {% for message in messages %}

                <div class="alert alert-success alert-dismissable" role="alert">

                    <button type="button" class="close" data-dismiss="alert" aria-label="close">

                        <span aria-hidden="true">x</span>

                    </button>


                {{message}}


                </div>


                {% endfor %}

                {% endif %}
                {% endwith %}


                <table class="table table-hover table-dark">

                    <tr>


                        <th>Date</th>
                        <th>Presenties</th>


                    </tr>


                   {% for row in a %}
                    <tr>
                        <td>{{row.date.strftime('%d-%m-%Y')}}</td>
                        <td>{{row.present}}</td>



                    </tr>


                  <!-- Modal Edit Employee-->


                    {% endfor %}


                </table>


            </div>



                  <!-- Modal Add Employee-->


<div id="mymodal" class="modal fade" role="dialog">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">

            <h4 class="modal-title">Add Entry</h4>
         </div>
         <div class="modal-body">

            <form action="{{url_for('core.attendance_add')}}" method="POST">
              <div class="form-group">

                 <label>Date</label>
                 <input type="text"  class="form-control" value={{date.strftime('%d-%m-%Y')}}>

              </div>


               <div class="form-group">

                  <label>Presenties</label>
                  <input type="text" name='present' class="form-control"  required="1">

               </div>


               <div class="form-group">

                  <button class="btn btn-primary" type="submit">Add entry</button>


               </div>


            </form>


         </div>


         <div class="modal-footer">


            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>


         </div>


      </div>


   </div>


</div>





        </div>

    </div>


      <script src="{{url_for('static',filename="js/jquery.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery-migrate-3.0.1.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/popper.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/bootstrap.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery.easing.1.3.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery.waypoints.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery.stellar.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/owl.carousel.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery.magnific-popup.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/bootstrap-datepicker.js")}}"></script>

      <script src="{{url_for('static',filename="js/jquery.fancybox.min.js")}}"></script>

      <script src="{{url_for('static',filename="js/aos.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery.animateNumber.min.js")}}"></script>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
      <script src="{{url_for('static',filename="js/google-map.js")}}"></script>
      <script src="{{url_for('static',filename="js/main.js")}}"></script>

</div>
</BODY>
</html>

cse_a/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Cse-a</title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Overpass:300,400,500|Dosis:400,700" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/open-iconic-bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/animate.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/owl.theme.default.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/magnific-popup.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/aos.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/ionicons.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap-datepicker.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/jquery.timepicker.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/flaticon.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/icomoon.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/fancybox.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">

  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
      <div class="container">
        <a class="navbar-brand" href="{{url_for('core.index')}}">CSE-A</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
          <ul class="navbar-nav ml-auto">
            <li id='mm' class="nav-item "><a href="{{url_for('core.index')}}" class="nav-link">Home</a></li>
            <li class="nav-item "><a href="{{url_for('core.donate')}}" class="nav-link">Assignments</a></li>
            <li class="nav-item"><a href="{{url_for("core.timeTable")}}" class="nav-link">Time table</a></li>

            <li class="nav-item"><a href="{{url_for("core.gallery")}}" class="nav-link">Gallery</a></li>
            <li class="nav-item"><a href="{{url_for('core.attendance')}}" class="nav-link">Attendance</a></li>
            <li class="nav-item"><a href="{{url_for('core.about')}}" class="nav-link">About</a></li>
            <li class="nav-item"><a href="{{url_for('core.contact')}}" class="nav-link">Contact</a></li>
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}

    {% endblock %}


  
  <footer class="footer">
    <div class="container">
      <div class="row mb-5">
        <div class="col-md-6 col-lg-4">
          <h3 class="heading-section">About Us</h3>
          <p class="lead">We are aspiring developers who love to implement what we learn and motivate others to do the same as well.</p>
          <p class='lead'>Learning never stops.You are only trapped in between the walls you built for yourself.Overcome and make your way through the walls because if you dont challenge yourself,you will never realise what you can become.</p>
          <p><a href="{{url_for('core.about')}}" class="link-underline">Read  More</a></p>
        </div>
        <div class="col-md-6 col-lg-4">
          <h3 class="heading-section">Recent Sites</h3>
          <div class="block-21 d-flex mb-4">
            <figure class="mr-3">

              <img src="static/images/corona.jpg" alt="" class="img-fluid">

            </figure>
            <div class="text">
              <h3 class="heading"><a href="http://coronaupdates123.herokuapp.com/">Corona Updates</a></h3>
              <div class="meta">
                <div><a href="#"><span class="icon-calendar"></span> march , 2020</a></div>
                <div><a href="#"><span class="icon-person"></span> Admin</a></div>

              </div>
            </div>
          </div>


        </div>
        <div class="col-md-6 col-lg-4">
          <div class="block-23">
            <h3 class="heading-section">Get Connected</h3>
              <ul>
                <li><span class="icon icon-map-marker"></span><span class="text"> St. Peter's Engineering College, Opp.A.P.Forest Academy, Maisammaguda, Medchal, Hyderabad, Telangana, India </span></li>
                <li><span class="icon icon-phone"></span><span class="text">9502841936</span></li>
                <li><a href="https://accounts.google.com/ServiceLogin/signinchooser?service=mail&passive=true&rm=false&continue=https%3A%2F%2Fmail.google.com%2Fmail%2F&ss=1&scc=1&ltmpl=default&ltmplcache=2&emr=1&osid=1&flowName=GlifWebSignIn&flowEntry=ServiceLogin"><span class="icon icon-envelope"></span><span class="text"></span>mahesh6273766@gmail.com</a></li>

              </ul>
            </div>
        </div>


      </div>

    </div>
  </footer>

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{{url_for('static',filename="js/jquery.min.js")}}"></script>
  <script src="{{url_for('static',filename="js/jquery-migrate-3.0.1.min.js")}}"></script>
  <script src="{{url_for('static',filename="js/popper.min.js")}}"></script>
  <script src="{{url_for('static',filename="js/bootstrap.min.js")}}"></script>
  <script src="{{url_for('static',filename="js/jquery.easing.1.3.js")}}"></script>
  <script src="{{url_for('static',filename="js/jquery.waypoints.min.js")}}"></script>
  <script src="{{url_for('static',filename="js/jquery.stellar.min.js")}}"></script>
  <script src="{{url_for('static',filename="js/owl.carousel.min.js")}}"></script>
  <script src="{{url_for('static',filename="js/jquery.magnific-popup.min.js")}}"></script>
  <script src="{{url_for('static',filename="js/bootstrap-datepicker.js")}}"></script>

  <script src="{{url_for('static',filename="js/jquery.fancybox.min.js")}}"></script>

  <script src="{{url_for('static',filename="js/aos.js")}}"></script>
  <script src="{{url_for('static',filename="js/jquery.animateNumber.min.js")}}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{{url_for('static',filename="js/google-map.js")}}"></script>
  <script src="{{url_for('static',filename="js/main.js")}}"></script>

  </body>
</html>

cse_a/templates/cd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Document</title>
</head>
<body>
    <div class="start">
        <a href="static/pdfs/compilerdesign.pdf" >
            <div class="combine">
                <img src="static/pdf.svg" width="100px" height="100px" alt="pdf image" style="align-items: center;">
                <p>CD all units</p>
            </div>
        </a>
    </div>



</body>

<style>
   
    div.start{
        align-self: center;
        padding: 20px;
        background-color: rgb(103, 187, 255) ;
        border-radius: .4em;
        margin: 10px;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        width: 100px;
        height: 200px;
       float: left;
    }

    div.start:hover{
        background-color: rgb(194, 227, 255);
    }

    p{
        padding-top:5px;
        text-align: center;
    }
</style>

</html>

cse_a/templates/challenge.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Cse-a</title>


    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Overpass:300,400,500|Dosis:400,700" rel="stylesheet">
    <link rel="stylesheet" href="{{url_for('static',filename='css/open-iconic-bootstrap.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/animate.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/owl.carousel.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/owl.theme.default.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/magnific-popup.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/aos.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/ionicons.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap-datepicker.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/jquery.timepicker.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/flaticon.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/icomoon.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/fancybox.min.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/bootstrap.css')}}">
    <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}">

  </head>
  <style>


    .op>#select{
      border : 0px solid grey;
      border-radius: 5px;
      height:25px;
      margin-left:2px;
    }
    textarea{
      resize:none;
    }
  </style>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-dark" id="ftco-navbar">
      <div class="container">
        <a class="navbar-brand" href="index.html">CSE-A</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="oi oi-menu"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="ftco-nav">
          <ul class="navbar-nav ml-auto">
            <li id='mm' class="nav-item "><a href="{{url_for('core.index')}}" class="nav-link">Home</a></li>
            <li class="nav-item "><a href="{{url_for('core.donate')}}" class="nav-link">Assignments</a></li>
            <li class="nav-item"><a href="{{url_for("core.timeTable")}}" class="nav-link">Time table</a></li>
            <li class="nav-item"><a href="{{url_for("core.gallery")}}" class="nav-link">Gallery</a></li>
            <li class="nav-item"><a href="{{url_for('core.attendance')}}" class="nav-link">Attendance</a></li>
            <li class="nav-item"><a href="{{url_for('core.about')}}" class="nav-link">About</a></li>
            <li class="nav-item"><a href="{{url_for('core.contact')}}" class="nav-link">Contact</a></li>

          </ul>
        </div>
      </div>
    </nav>

<br><br><br><br>

<form class="" action="{{url_for('core.challenge',id=ele.id)}}" method="post">
<div class="container">

  <div class="jumbotron">

    <h1>{{ele.title}}</h1>
    <br><br>


      {%set s=ele.description.split('\n')%}

      {%for i in s%}
        <p>{{i}}</p>
      {%endfor%}



  </div>


</div>
<br><br>
<br>
<div class="container">
  <div class="jumbotron">

      <div class="op">
        <select name="lang" id="select">
          {%for i in languages%}
            <option >{{i}}</option>
          {%endfor%}
        </select>
      </div>
      <hr>

      <div class="ide">

        <div class="container">
          <div class="jumbotron">



              <label for="code">code</label>
              <textarea cols="120" rows="16" name="code" id="code" placeholder="Write your code here.."style="overflow-y: auto; width: 100%; height: 60%; display: inline; font-size: 15px;font-family: consolas;" wrap="off">{{code}}</textarea>
              <label for="input">input</label>
              <textarea cols="60" rows="5" name="input" id="input" placeholder="give inputs only if you have any!"style="overflow-y: auto; width: 100%; height: 60%; display: inline; font-size: 15px;font-family: consolas;" wrap="off"></textarea>
              <input type="submit" name="" value="Run"><br><br><br>
              <p>
                {%if output["statusCode"]==200%}<strong>Status</strong>:Executed Successfuly{%else%}<strong>Status</strong>:Error{%endif%}<strong style="padding-left: 4em;">Time</strong>:{{output['cpuTime']}} sec<strong style="padding-left: 4em;">Memory</strong>:{{output['memory']}} bytes</p>
              <label for="output">Output</label>
              <textarea cols="80" readonly rows="8" name="input" id="output" style="overflow-y: auto; width: 100%; height: 60%; display: inline; font-size: 15px;font-family: consolas;" wrap="off">{{output['output']}}</textarea>


          </div>

        </div>
      </div>


  </div>
</div>
  </form>

                  </script>

      <script src="{{url_for('static',filename="js/jquery.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery-migrate-3.0.1.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/popper.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/bootstrap.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery.easing.1.3.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery.waypoints.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery.stellar.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/owl.carousel.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery.magnific-popup.min.js")}}"></script>
      <script src="{{url_for('static',filename="js/bootstrap-datepicker.js")}}"></script>

      <script src="{{url_for('static',filename="js/jquery.fancybox.min.js")}}"></script>

      <script src="{{url_for('static',filename="js/aos.js")}}"></script>
      <script src="{{url_for('static',filename="js/jquery.animateNumber.min.js")}}"></script>
      <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
      <script src="{{url_for('static',filename="js/google-map.js")}}"></script>
      <script src="{{url_for('static',filename="js/main.js")}}"></script>

</div>
</BODY>
</html>